### ISSUE TITLE
On ./submit stage of installation

### ISSUE THREAD

**Issue by jjacks95** [graphsense/graphsense-transformation#14]
When attempting the submit stage of installing graphsense transformation I get a SparkSubmit error from not load the TransformationJob class

Error:
```
19/04/25 22:57:21 WARN DependencyUtils: Local jar /home/dockeruser/graphsense-transformation/target/scala-2.11/graphsense-transformation_2.11-0.4.0.jar does not exist, skipping.
19/04/25 22:57:21 WARN DependencyUtils: Local jar /root/.ivy2/local/at.ac.ait/graphsense-clustering_2.11/0.4.0/jars/graphsense-clustering_2.11.jar does not exist, skipping.
19/04/25 22:57:21 WARN SparkSubmit$$anon$2: Failed to load at.ac.ait.TransformationJob.
java.lang.ClassNotFoundException: at.ac.ait.TransformationJob
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/04/25 22:57:21 INFO ShutdownHookManager: Shutdown hook called
19/04/25 22:57:21 INFO ShutdownHookManager: Deleting directory /tmp/spark-0623bdfa-3959-4d2c-a6c7-8364305461af
```
Any help would be appreciated.

**Comment by jjacks95** [comment]
Fixed the problem had to do with the way I loaded blocksci export into casssandra.
