### ISSUE TITLE
GitHub action fails after Spark upgrade - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by defconst** [graphsense/graphsense-transformation#68]
Spark upgraded to version 3.2.1 (from 3.1.2)

Github action for `sbt test` fails with `java.lang.OutOfMemoryError: Java heap space`
Runtime of tests much longer (almost 9 minutes) 

```
Clustering without coinjoin inputs
Clustering with coinjoin inputs
[info] TransformationTest:
[info] info.graphsense.TransformationTest *** ABORTED *** (21 milliseconds)
[info]   java.lang.OutOfMemoryError: Java heap space
[info]   at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
[info]   at java.lang.StringBuilder.<init>(StringBuilder.java:106)
[info]   at org.apache.spark.sql.catalyst.util.StringUtils$StringConcat.toString(StringUtils.scala:139)
[info]   at org.apache.spark.sql.catalyst.util.StringUtils$PlanStringConcat.toString(StringUtils.scala:166)
[info]   at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:230)
[info]   at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.onUpdatePlan(AdaptiveSparkPlanExec.scala:706)
[info]   at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$2(AdaptiveSparkPlanExec.scala:239)
[info]   at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec$$Lambda$1944/464226847.apply$mcVJ$sp(Unknown Source)
[info]   at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
[info]   at scala.Option.foreach(Option.scala:407)
[info]   ...
[error] Uncaught exception when running info.graphsense.TransformationTest: java.lang.OutOfMemoryError: Java heap space
```

**Comment by mdragaschnig** [comment]
Cause:  By default, [JVM uses 1/4 of available](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gc-ergonomics.html) memory as maximum heap size. [Github-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) have 7G RAM, 1/4 of which is < 2G.

The unit (...)  tests currently require at least 3G RAM heap size -> OOM error.

Fix: Setting the [appropriate limit for forked tests](https://www.scala-sbt.org/1.x/docs/Forking.html) in build.sbt.
